### ISSUE TITLE
Lack of Style Options for Spaces in Full Help View Columns

### ISSUE THREAD

**Issue by rrrodzilla** [charmbracelet/bubbles#572]
https://github.com/charmbracelet/bubbles/blob/a9344b59531d1b947978485dea07c5597299889a/help/help.go#L197-L201

In the FullHelpView function, the spaces within the columns created by lipgloss.JoinHorizontal do not have dedicated style options. This results in inconsistent styling, especially when a background color is applied to the terminal. As shown in the attached screenshot, the spaces remain unstyled with no ability to apply custom styles, leading to visual discrepancies.

This issue is similar to the one described in issue #571, where the ShortHelpView function lacks style options for spaces between the key and description.

Screenshot: 
![image](https://github.com/user-attachments/assets/1f483e15-3c7a-4f54-abdc-9e0e8cd55c1b)

To resolve this issue, I suggest wrapping the JoinHorizontal call in a Render call of the FullSeparator style. This would allow the other styles to override anything not set by the FullSeparator style, effectively styling the whitespace.

If you settle on an approach, I'm happy to implement it and provide a PR. Thanks again!

**Comment by bashbunni** [comment]
Hey, this is a bug with `JoinVertical` and `JoinHorizontal` in Lip Gloss. We're working on a new version that should fix this. Thank you for bringing it to our attention though, I was only able to reproduce this in a very specific situation before, so this gives us more to work with and room for improving our test coverage. Thank you!!

**Comment by joelzwarrington** [comment]
@bashbunni any update on this issue? 

This [line](https://github.com/charmbracelet/bubbles/blob/8585ef868b06480f95c2927a33cc0f440630c502/help/help.go#L214) is unstyled so it's difficult to style the background of the help bubble.

**Comment by bashbunni** [comment]
Hey joel, I'm no longer maintaining this tool but you can possibly get help from  @andreynering 

The new version I was talking about was v2 lipgloss and bubble tea, I'd recommend trying that if you haven't already :)

**Comment by joelzwarrington** [comment]
👋 @bashbunni thanks for following up nonetheless! The issue persists on v2

**Comment by bashbunni** [comment]
@joelzwarrington rip :(
